### ISSUE TITLE
Fix Leaderboard Rankings

### ISSUE THREAD

**Issue by david-courtis** [RelativelyFine/COMPSA-Frontend#11]
The current leaderboard rankings indicate that if _m_ people are tied for rank _n_, their displayed rank would be _n_
The proper way to show this is to indicate that if _m_ people are tied for rank _n_, their displayed rank would be _n + m - 1_

This will encourage users to snatch a higher rank.

ie.
 4 people are tied for rank 3.

m = 3, n = 4

Displayed rank = 3 + 4 - 1 = 6
All people are tied in the displayed rank 6, and there is no displayed rank 3,4, or 5.

**Comment by amaanjaved1** [comment]
Updated code within profiles component
