### ISSUE TITLE
Change About Page Images

### ISSUE THREAD

**Issue by david-courtis** [RelativelyFine/COMPSA-Frontend#5]
In the about component, each photo is outdated (filled with last year's). We have just completed the 2022 compsa photoshoot and now we must update these images with their respective photo.

The drive for these new photos are here: [https://drive.google.com/drive/folders/1Zg5VRh8RCq6YM8GnwVgiPH-BZAKHE9XW](https://drive.google.com/drive/folders/1Zg5VRh8RCq6YM8GnwVgiPH-BZAKHE9XW)

All titles will have their respective photo in the drive, you can pick the most suitable photo.

An additional section must also be appended to the page for the Tech Team. This consists of:
	
Backend Intern	        Nathan Cai
Frontend Intern	        Adwait Srivastava
Frontend Developer	David Courtis, Kunalan Kevin Subagaran
Design Intern	                Shabicha Sureshkumar	
UI/UX Intern	                Anna Lou	
UI/UX Designer	        Amy Cui	
Backend Developer	        Logan Cantin	

This is to be styled the same way as the other sub-sections of meet the team.

**Comment by AdwaitSri** [comment]
Hi, 

I would like to work on this issue. I request you kindly assign the issue to me. 
Thank You
