### ISSUE TITLE
Create Contact Page

### ISSUE THREAD

**Issue by david-courtis** [RelativelyFine/COMPSA-Frontend#6]
The existing contacts page is blank. 
This ticket is dedicated to the creation of the contacts page, in both mobile and desktop view.

The design for such page can be found here: [https://www.figma.com/file/qZRhKjPCQzlEaLf5UR6Q1d/COMPSA-website?node-id=2%3A2](https://www.figma.com/file/qZRhKjPCQzlEaLf5UR6Q1d/COMPSA-website?node-id=2%3A2)
Use the design will the fullscreen map. Changes may be made in the future.

The mobile view has 3 pages, the first page's two buttons will take the user to the other two pages. (Can be seen in the figma)

Notes:
The concerns or Feedback button should redirect the user to their email application. This can be done by setting the href to "mailto:feedback@compsa.queensu.ca"

Disregard the updated navbar design in the page.

Specific portfolios should currently have an empty href - this will be implemented once the respective pages are complete.

**Comment by mnosov622** [comment]
Hi !

I would love to create contact page. Could you assign this issue to me, please?

**Comment by david-courtis** [comment]
Completed by @amaanjaved1
