### ISSUE TITLE
Draft - Professional Development Page

### ISSUE THREAD

**Issue by david-courtis** [RelativelyFine/COMPSA-Frontend#9]
The design and management team have deemed it necessary to create an PD section on the site.
The specifics of the design for this will likely be reiterated as relevant (text descriptions, photos, api)
Currently, no backend integration is necessary.

You are responsible for creating the page for desktop view.

The desktop design for this site can be found here https://www.figma.com/file/qZRhKjPCQzlEaLf5UR6Q1d/COMPSA-website?node-id=2%3A2

Notes:
This page will not be ready for production at the end of this ticket, so don't stress about the specific information (href links, names, images, etc.). Only the structure needs to be implemented. Do so as shown in the figma.
Don't update the navbar. Don't allow this page to be accessible.

**Comment by AdwaitSri** [comment]
Professional development page ready
